sudo: false
cache:
  directories:
  - "$HOME/.gradle"
  - "$HOME/.m2/repository"
jdk:
- oraclejdk7
dist: precise
addons:
  apt:
    sources:
    - mongodb-upstart
    - mongodb-3.0-precise
    packages:
    - mongodb-org-server
    - mongodb-org-shell
env:
  global:
  - TERM=dumb
  - MALLOC_ARENA_MAX=1
  - GRADLE_OPTS="-Xmx768m -Xms256m -XX:MaxPermSize=256m -XX:+CMSClassUnloadingEnabled"
  - GIT_NAME="Graeme Rocher"
  - GIT_EMAIL="graeme.rocher@gmail.com"
  - secure: esiCb14Zo1wSIawRZFf65TMsDidzLDNoBcCWQnF75is+J972j4Kbz9JXy56iJZCvqChZUaD1srT9+gajfgrnV0niIW3dx0RRYTaALuGPzsWm+/4CMxjY8YY5fhF37KHi/bg0KnBXrcyf5QjJTkAmlwVbCjuUG9+axpjekpfgYzK41xB5juOmIul4LXvXvAaf7kkZ01QIDav5n0JouwFHZ0bUjRM7kxfiZQ43f1W/5uL1SWEwgpzF5uQgNTd3IowWRO1fFi0ANSKxfxn9TxsM0uN1/8fBYxgcF2FdWeJIQG3jZ2KLYmaSx0gndwqyF9fHfzb1lE7+HZ2PGvilEh2yeonC0pTjgVQ7oncc/KPcBThPkmWvQSGnD9hxxEpqk6S76vaqiVqleW7jd2njN2941KW5DgSIcUHKcDaoH1L+VpE+sGaV4jEk+R0B76A8gnDn4EIyGV3rjkFNx7iQQGtUPe2jyl//yJj3sfzXWbDX9PnFgvlvd7YGXeZEyTZNelbMU3YAvQouavJwrpm9BdF7elnvpLVkeyzJdr/2CiIZtXAsSSNruwxzO8pRaYNUw6UJ47w/iNs5YRsUYw4KXEgHNLwAENBH6IksKAs3xFuWE/K98x/jiW23NzjlQcNre+5rbuvGy4dNyuX71imya4SMB8C4Wopihuw37PYwXazoA/0=
script: "./travis-build.sh"
install: false
